### ISSUE TITLE
Model for R9.4?

### ISSUE THREAD

**Issue by yoshihikosuzuki** [al-mcintyre/mCaller#1]
Hi, I'm very excited to try your algorithm.

I'm just wondering whether you have a model for R9.4 flow cells. "model_NN_6_m6A.pkl" or "mod_NN_6_m6A.pkl" is the one?

**Comment by al-mcintyre** [comment]
mod_NN_6_m6A.pkl is the correct one for R9.4, r95_model_NN_6_m6A.pkl for R9.5. 

model_NN_6_m6A.pkl is the default name when you train a new model, but the uploaded version is trained on very limited test data.

**Comment by yoshihikosuzuki** [comment]
I got it, thanks a lot!

**Comment by xingjianfeng100** [comment]
Hi ,I don't find the "model_NN_6_m6A.pkl" or "mod_NN_6_m6A.pkl" in the web, how can I download it ?

**Comment by al-mcintyre** [comment]
Sorry about that, I've re-added it as "r94_model_NN_6_m6A.pkl"

**Comment by xingjianfeng100** [comment]
thank you very much @al-mcintyre ，it works . 
And another problem is the positions.txt file , there seem to be  no mention about method to get it in paper,so how can I get it?
