### ISSUE TITLE
Problems about run of Test Data

### ISSUE THREAD

**Issue by OliverG74** [al-mcintyre/mCaller#10]
Dear authors,
when we run the command line:

./make_bed.py -f testdata/masonread1.eventalign.diffs.6 -d 1 -m 0.5

the error says that programm 'make_bed.py' cannot recognize the argument "-m 0.5"
we don't understand why '-m 0.5' cannot be recognized as an argument when running this file.

**Comment by al-mcintyre** [comment]
Sorry please try with the updated flag for the modification threshold `-t 0.5`. I will update the README
