### ISSUE TITLE
why the m6A result significantly  focus on some genome region by using this software

### ISSUE THREAD

**Issue by yue9404** [al-mcintyre/mCaller#11]
i have 20x nanopore datasets, and i use this software to call m6A genome loci. however, the result show that the m6A loci significantly focus on some genome region.  i wonder whether the nanopre datasets suit for m6A analysis and the result of this software was  convincing. 
Because i have other 10x PacBio datasets. Although the reference genome is different,  the m6A distribution result of PB was  better than nanopre.

**Comment by al-mcintyre** [comment]
Hello, thank you for your inquiry. As we show in our paper (https://www.nature.com/articles/s41467-019-08289-9), calling m6A from nanopore data produces more false positives than using PacBio data in general. It is difficult to comment further without more information on your genome of interest (eukaryotic? bacterial/archaeal?) or your results. 

I would suggest trying to use the same reference genome for a direct comparison and perhaps using our plotting option for make_bed.py to visualize current deviations for particular loci of interest (see `make_bed.py --help` for details). 

For more advice on dealing with metazoan m6A calling, see comments here: https://github.com/al-mcintyre/mCaller/issues/9

**Comment by yue9404** [comment]
Thanks for your answering. i have two eukaryotic reference genome and corresponding 20x nanopore dataset., i wonder whether i should train some modle before i use mCaller to detect m6A? Or which m6A modle proveied by the software is suit for eukaryotic m6A detecting?  Dose these make the m6A result different?

**Comment by al-mcintyre** [comment]
Unless you know the sequence motif where m6A is found in your species of interest, I would suggest just using the E.coli-trained models provided, with selection depending on your flowcell version (R9.4 or R9.5). Best thing would be to focus on validating positions identified by PacBio as well, assuming that data is from the same species or individual.

**Comment by yue9404** [comment]
i used the "r95_twobase_model_NN_6_m6A.pkl"  E.coli-trained models provided, but i don't have corresponding PacBio datasets. when i detect 6mA by using -m A. should i only use the -m GATC to detect 6mA? Or what meaing of -p position.txt

**Comment by al-mcintyre** [comment]
No, GATC is the target motif of the Dam enzyme found in E. coli; I wouldn't suggest focusing on that motif for eukaryotic DNA. If you want to test specific positions rather than every adenine in the genome, the `-p` flag provides an option to focus on the positions listed in a .txt file.

**Comment by yue9404** [comment]
thanks for answering, i throught the only 20x dataset might result in the significantly focusing on some regions.

**Comment by al-mcintyre** [comment]
Keep in mind the depth threshold `-d` for make_bed.py. The default is 15 and you can lower this if desirable.
