### ISSUE TITLE
mCaller with position file returns no results

### ISSUE THREAD

**Issue by russellj7** [al-mcintyre/mCaller#12]
Hello,

Thank you for making mCaller! I think it's a nice alternative to using tombo.

I have a position file for all the 'A' sites I want to check for m6A, however when I use the -p option with my positions file, mCaller returns an empty file. My positions file is formatted as tab separated exactly how is described in the "testdata" (with chromosome, position and strand). I left out the label column because I am not re-training. Adding a label column gives the same result. Is there any troubleshooting I can do to get the positions file working? 

In the meantime, instead of using a positions file, I tried mCaller by motif. I'm working with a motif that includes an ambiguous nucleotide 'N'. The motif is 'GANTC'. Running mCaller with 'GANTC' returns no result. I then tried running mCaller on each possible motif individually (i.e. GAATC, GAGTC, GATTC, GACTC) and it worked! However in the results for GAATC, I noticed mCaller is labeling both A positions as modified (ex. 'TAAT**GMMTC**CT'). Only the first A position can be modified for this particular motif (i.e. 'GMATC'). How can I tell mCaller to only consider the first 'A' in this situation?

Thank you!

**Comment by al-mcintyre** [comment]
Hi,

Have you double checked that the positions in your file correspond to adenines (and are not, for instance, off by one) and that the contig names match your fasta file? If you want to send me your file (abm237 at cornell.edu), I can take a look, although it may be difficult for me to debug without seeing your data beyond the obvious column formatting points. The label column shouldn't matter. 

mCaller doesn't currently recognize ambiguous bases and there is currently no way to specify bases within motifs (you can always sort out after running mCaller), but I will look into implementing these features. 

Thanks for your feedback!

**Comment by russellj7** [comment]
I think my positions file had 2 issues. 1) my chromosome name had spaces and special characters, so I simplified the name and 2) after fixing the chromosome name, I received an error that my positions were not 0-indexed, so I subtracted 1 from each position. I'm trying the new positions file now and will post back when it finishes.

For the case of 'GAATC', is mCaller predicting the probability that both A positions are modified simultaneously? If so, I'm not sure how I would go about filtering the resulting table for just the probabilities of the first 'A'.

**Comment by al-mcintyre** [comment]
The predictions are basewise for the provided models, but any base for which a methylation prediction will be made is marked as M in the table. 

Let me know if those changes to the position file work.

**Comment by russellj7** [comment]
Hello and happy Monday!

The new 0-based positions file worked! 

If I understand the output correctly, I now have a .tsv file for each read covering the specified positions and a probability that the 'A' at each position is methylated. It looks as though positions with a probability of methylation greater than 0.5 are labeled as methylated by mCaller, is that correct? 

I suppose my next step might be to average the probabilities for each position to determine an average methylation status for my motif across the entire genome (sticking with mCaller's cutoff of 0.5). 

Thank you again for your help! It's much appreciated!

**Comment by al-mcintyre** [comment]
Sorry for the delay. Glad it worked! Yes, that's right. You can use the make_bed.py script to summarize across reads for each position.
