### ISSUE TITLE
Could mCaller detect methylation from other species

### ISSUE THREAD

**Issue by lemonsky123** [al-mcintyre/mCaller#13]
Hi @ralowe, @al-mcintyre Could mCaller detect methylation from other species, such as human?
Best.

**Comment by al-mcintyre** [comment]
Hi there. Yes, in theory mCaller could detect methylation from other species. As we show in our manuscript, it helps to train a model using sequence contexts that correspond to those you're interested in measuring, if possible. Given the error rates of methylation predictors for nanopore data and the low predicted abundance of 6mA in metazoan DNA (if that is the base you're interested in), I would also be cautious in interpreting the output of the tool, and you may want to filter results by comparing those from several different predictors. Also see the discussion here: https://github.com/al-mcintyre/mCaller/issues/9
