### ISSUE TITLE
probable mCaller python error

### ISSUE THREAD

**Issue by fisseb4** [al-mcintyre/mCaller#14]
Hi,

I try to run mCaller on Pseudomonas aeruginosa and it works good for known motifs. Just for reasons of curiosity I wanted to check for all As to see if it is possible to detect methylated As that are not in a motif. I tried the -m A option to state the motif to be only A and in a second try I tried a 0-based position file with all As of the reference genome. Unfortunately both time the same error occurs:

61c7c0c1-6316-41d3-92cc-a98fa60e0d9a	1128158	GTNNNMNCNGG	2.35,2.21,-2.36,-1.9133333333333333,-3.805,-3.745,18.353837395288313	+ - Index or Key Error
['MG', 'MH'] ['AA', 'AC', 'AG', 'AM', 'AT', 'MG', 'MA', 'MC', 'MM', 'MH', 'MT'] MN
'MN'
[[0.32129482 0.67870518]]

I think this is some python error. Do you have an idea how to fix this problem? Thank you for your help in advance!

Cheers
Sebastian

**Comment by al-mcintyre** [comment]
Hi Sebastien, 
It looks like you may have ambiguous characters (Ns) in your reference genome, which aren't currently supported in our models. Can you check if this is the case?

**Comment by fisseb4** [comment]
Hi,

thank you for your fast reply. I checked the reference and indeed there are a few Ns that I was not aware of. I will fix this and rerun mCaller.
