### ISSUE TITLE
License info missing

### ISSUE THREAD

**Issue by smoe** [al-mcintyre/mCaller#16]
Hello,
We are in the last minutes of this month's Debian Covid-19 Hackathon and would very much like to redistribute mCaller with the Linux distribution and other software that depends on it. Could you specify one, please, so we know we are allowed to redistribute your work?
Many thanks and regards,
Steffen

**Comment by al-mcintyre** [comment]
Done -- hope it's useful.

**Comment by smoe** [comment]
Record time - fantastic!
