### ISSUE TITLE
Errors on running mCaller

### ISSUE THREAD

**Issue by clarepacini** [al-mcintyre/mCaller#2]
Hi,
I've just completed a first run using mCaller. The process has completed and I have output although the following error is repeatedly shown in the log output as well:
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/home1/gurdon/cep46/mCaller/mCaller_nanopolish.py", line 46, in worker
    outtup = extract_features(tsvname,fastaname,read2qual,nvariables,skip_thresh,qual_thresh,modelfile,classifier,startline,endline=endline,train=train,pos_label=training_pos_dict,base=base,motif=motif,positions_list=positions_list)
  File "/mnt/b2/home1/gurdon/cep46/mCaller/extract_contexts.py", line 138, in extract_features
    while tsv.tell() <= endline-500:
OSError: telling position disabled by next() call

Is this error something I should be worried about?

Best,

Clare

**Comment by al-mcintyre** [comment]
Hi Clare, 
mCaller is currently compatible only with python 2.7. You can try that and let me know how it goes, or I had some issues with the file merging and am planning to push an updated version within the next few days if you can hold off until then. 
Thanks,
Alexa

**Comment by clarepacini** [comment]
Hi Alexa,

Thanks for this. I may have to wait for the updated version as I can't get it to run with python2.7. The output that I have running for python3 appears to be truncated as I have less that 10x coverage output when my dataset has 100x coverage. For some reason mCaller can't find the correct version of scikit-learn when running python 2.7:
Traceback (most recent call last):
  File "/mnt/home1/gurdon/cep46/mCaller/mCaller_nanopolish.py", line 18, in <module>
    from train_model import train_classifier,pos2label
  File "/mnt/b2/home1/gurdon/cep46/mCaller/train_model.py", line 3, in <module>
    from sklearn.model_selection import RandomizedSearchCV
ImportError: No module named model_selection

Even though I have the same packages installed for python2.7 and python3.5:
<img width="1610" alt="screen shot 2018-02-04 at 10 53 55" src="https://user-images.githubusercontent.com/2804066/35776724-bd9eb2a0-0999-11e8-87ad-e6f26dc81eaa.png">

Looking forward to the update!

Thanks,
Clare

**Comment by al-mcintyre** [comment]
I'm surprised it ran at all with python3.5; I get heaps of errors and wouldn't advise this. 
When using python2.7, if you try `which python` from the command line and, from python, `import sklearn` + `print sklearn.__version__`, do you see what you expect? I would recommend using a conda environment to set up a separate installation.  
Note that unless you force mCaller to include examples with skips in the current, the coverage won't be exactly what you expect. Depending on the data set, we normally lose around a quarter of the depth. 
Finishing some last tests and I'll push an update later today with a new model that's better able to detect methylation in AG contexts.

**Comment by al-mcintyre** [comment]
Hi Clare, 
Did you get it running? 
The model is now updated and the results across different restriction site motifs are posted in the README. Check it out- may or may not be suitable for your purposes, depending on your species of interest.

**Comment by clarepacini** [comment]
Hi Alexa,

Yes thanks, I did manage to get it running. Thanks for the update on the README - should help when we are assessing our data. We’re just in the process of analysing our results and are thinking about training a model based on our data for eukaryotes using mCaller.
Cheers,

Clare
