### ISSUE TITLE
Facing an issue for the 'nanopolish eventalign' command

### ISSUE THREAD

**Issue by aim95** [al-mcintyre/mCaller#22]
For detecting 6mA modifications, I am currently working on mCaller and following the instructions under 'Pipeline for methylation detection from R9 data'. The extracting and aligning commands generated the required files, but the nanopolish eventalign command couldn't be executed. 
I gave the following command: nanopolish eventalign -t 1 --scale-events -n -r trytry.fastq -b trytry.sorted.bam -g Desktop/Thesis/example/reference.fasta trytry.eventalign.tsv
But the following error occurred: 
contig position reference_kmer read_name strand event_index event_level_mean event_stdv event_length model_kmer model_mean model_stdv standardized_level
[bam process] iterating over region: trytry.eventalign.tsv
[E::sam_itr_next] Null iterator

I would be greatly pleased if you could help me out. 
Thankyou.

**Comment by al-mcintyre** [comment]
Hi there, 
It looks like you've also posted this issue [on the nanopolish github page](https://github.com/jts/nanopolish/issues/863). Try that fix, and I can help you out if you have any problems with the mCaller commands later. 
Best,
Alexa

**Comment by aim95** [comment]
Sorry for the confusuion. That error was solved. Thankyou.

**Comment by aim95** [comment]
Sorry for the confusion. The error was sorted out. Thankyou.
