### ISSUE TITLE
Facing an issue with the command to detect 6mA

### ISSUE THREAD

**Issue by aim95** [al-mcintyre/mCaller#23]
The 5th step under 'Pipeline for methylation detection from R9 data' is to run mCaller to detect 6mA modifications
The following command was given: mCaller/mCaller.py -m GATC -r Desktop/Thesis/example/reference.fasta -d mCaller/r95_twobase_model_NN_6_m6A.pkl -e trytry.eventalign.tsv -f trytry.fastq -b A 

But the following error occured: 
17 contigs
1 threads
Traceback (most recent call last):
  File "mCaller/mCaller.py", line 187, in <module>
    main()
  File "mCaller/mCaller.py", line 184, in main
    args.train,modelfile,args.skip_thresh,args.qual_thresh,args.classifier,training_tsv,args.plot_training)
  File "mCaller/mCaller.py", line 58, in distribute_threads
    extract_features(tsvname,refname,read2qual,nvariables,skip_thresh,qual_thresh,modelfile,classifier,0,endline=bytesize,train=train,pos_label=training_pos_dict,base=base,motif=motif,positions_list=positions_list) 
  File "/home/arm/mCaller/extract_contexts.py", line 143, in extract_features
    while tsv.tell() <= endline-500: #TODO: why 500? 
OSError: telling position disabled by next() call

I would be greatly obliged if you could help me out.
Thankyou.

**Comment by al-mcintyre** [comment]
Hi, 
It's an issue with the recent update to python3. I am taking a look and will let you know once I've found a workaround.

**Comment by aim95** [comment]
Sure Sir.

**Comment by al-mcintyre** [comment]
Ok, I've uploaded a new version of extract_contexts.py, and it should be working now -- can you try with the updated script?

**Comment by aim95** [comment]
I tried with the updated script and finally got a .bed file at the end of 6th step. Thankyou Sir.
