### ISSUE TITLE
Can't run the methylation detection script

### ISSUE THREAD

**Issue by gsukrit** [al-mcintyre/mCaller#26]
Unable to run the mCaller.py -m GATC script with the following error thrown. Please assist. 

/home/adas/mCaller-master/mCaller.py -m GATC -r Pv_wholegenome_Seq.fasta -d r94_model_NN_6_m6A -e mCal.eventalign.tsv -f barcode1_merged.fastq -b A 
Traceback (most recent call last):
  File "/home/adas/mCaller-master/mCaller.py", line 187, in <module>
    main()
  File "/home/adas/mCaller-master/mCaller.py", line 157, in main
    assert os.path.isfile(modelfile), 'model file not found at '+modelfile
AssertionError: model file not found at r94_model_NN_6_m6A

**Comment by al-mcintyre** [comment]
Hi, I looks like `r94_model_NN_6_m6A` is not in the folder you're running mCaller from. Check that the file exists by that name and its location. You may also be missing a file suffix (e.g. `.pkl`).

**Comment by al-mcintyre** [comment]
Hello, please let me know if this issue is not resolved. I will close it for now.
