### ISSUE TITLE
'could not find sequence for reference contig'

### ISSUE THREAD

**Issue by kewei2019** [al-mcintyre/mCaller#27]
Hi all,
Thank you for the amazing tool. I applied mcaller to detect GATC methylation on my nanopore data, but an error showed up. I can share the fastq, tsv, and ref file if needed. Thanks for your help!
Kewei Xu
![image](https://user-images.githubusercontent.com/52051945/114948284-eb090d80-9e0b-11eb-8a91-de0165780c7e.png)

**Comment by al-mcintyre** [comment]
Take out the header line in the nanopolish tsv file to solve the "could not find sequence for reference contig contig" error. I will implement a fix for this soon. 

It looks like the program actually fails for another reason in your case though: can you send me the first few lines of your nanopolish tsv and a few example read names from your fastq?

**Comment by kewei2019** [comment]
Yes, thanks!
Here is the tsv file, named '2.txt' and the part of the fastq file, named '3.txt'.
Kewei
[2.txt](https://github.com/al-mcintyre/mCaller/files/6327898/2.txt)
[3.txt](https://github.com/al-mcintyre/mCaller/files/6327906/3.txt)

**Comment by al-mcintyre** [comment]
Hi Kewei, 
I'm just installing the new version of nanopolish now; can you run nanopolish to generate a tsv with read_name instead of read_index? The read names are necessary to match up with those in the fastq file for quality calculations.

**Comment by al-mcintyre** [comment]
Try the flag `-n` or `--print-read-names` when you run nanopolish eventalign.

**Comment by kewei2019** [comment]
Hi,
Here are the tsv file and the fastq file. Thanks!
[tsv_file.txt](https://github.com/al-mcintyre/mCaller/files/6338086/tsv_file.txt)
[fastq_file.txt](https://github.com/al-mcintyre/mCaller/files/6338087/fastq_file.txt)

**Comment by al-mcintyre** [comment]
Hi, this looks good. Are you still getting an error when you try to run mCaller?

**Comment by kewei2019** [comment]
Hi,
Yes! It looks great! By the way, if I want to detect all the methylated A instead of GATC motif, what command I should use?

I type in the following code for detecting GATC methylation:
python3 ~/program/mCaller/mCaller/mCaller.py -m GATC -r GCA_002057885.1_ASM205788v1_genomic.fna -d ~/program/mCaller/mCaller/r95_twobase_model_NN_6_m6A.pkl -e 1.txt -f 37ad_combined.fastq -b A

And what is the title for each raw? 
![image](https://user-images.githubusercontent.com/52051945/115302839-1a778d00-a120-11eb-9f57-3d696b50c2c5.png)

Best,
Kewei

**Comment by al-mcintyre** [comment]
Just replace `-m GATC` with `-m A` in your command. 

Columns indicate chromosome, read name, genomic position, position k-mer context, features (current deviations), strand, label, and probability of methylation predicted by mCaller for that position and read

**Comment by kewei2019** [comment]
Thank you very much!
Kewei
