### ISSUE TITLE
Pickle file search path not clear

### ISSUE THREAD

**Issue by Shians** [al-mcintyre/mCaller#30]
I tried running 

```
mCaller.py <-m GATC or -p positions.txt> -r <reference>.fasta -d r95_twobase_model_NN_6_m6A.pkl -e <filename>.eventalign.tsv -f <filename>.fastq -b A 
```

with the variables set for my data, however mCaller didn't find r95_twobase_model_NN_6_m6A.pkl. I found the absolute path of the file and use that as an argument, but was it meant to be able to locate the file within its own installed folder, or did the pickle need to be in the local path?

**Comment by al-mcintyre** [comment]
The pickle either needs to be in the local path or the absolute path should be provided as an argument.
