### ISSUE TITLE
Motif context

### ISSUE THREAD

**Issue by vahidAK** [al-mcintyre/mCaller#32]
Hi,

I was wondering which in which sequencing contexts (e.g. GATC) mCaller can predict methylated adenine? 

Thanks,
Vahid

**Comment by al-mcintyre** [comment]
Hi Vahid, 

mCaller can predict methylation at any sequencing motif using the flag `-m A`, or at the specific motif of your choice (e.g. using the flag `-m GATC`). Performance does vary by motif. The original models were trained on GATC sites, and the barchart in the readme highlights differences in accuracy when applied to other motifs. The newest models are labelled by their training motifs (`CAAYNNNNNRTAC_model_6_m6A.pkl` and `CRAANNNNNNNTGC_model_6_m6A.pkl`). If possible, I would suggest training on a similar motif using data produced using the same flowcell and basecaller versions, but the provided models could also be suitable depending on your analysis question.
