### ISSUE TITLE
whether the newest models are suited for R9.41 flowcell data

### ISSUE THREAD

**Issue by mantonglaw** [al-mcintyre/mCaller#33]
Our nanopore DNA sequencing data comes from R9.41 flowcell. I wonder wheter  the newest models  such as CAAYNNNNNRTAC_model_6_m6A.pkl and CRAANNNNNNNTGC_model_6_m6A.pkl, are suitable to detech 6mA modification in fast5 data from R9.41 flowcell.

**Comment by al-mcintyre** [comment]
They were not built for R9.41 data, but may be worth trying. In the past I found some success applying R9.4 models to R9.5 data and vice versa, but you will need to test whether the models are extensible in this case (also for your motif(s) of interest).
