### ISSUE TITLE
method to get the POSITIONS.txt

### ISSUE THREAD

**Issue by xingjianfeng100** [al-mcintyre/mCaller#4]
Hi， @al-mcintyre 
        The positons.txt that you mention in the "README",which "with a list of positions at which to classify
 bases (must be formatted as space- or tab-separated  file with chromosome, position, strand, and label if
 training) , can't be obtain in simple way,would you please  show method to get POSITIONS.txt in detail?
         And in testdata folder,there are three positons file(e,g, test_positions.txt,test_positions_A.txt, test_positions_m6A.txt), do we need so many positions file to methylation call?  And what they do  in  our test?

**Comment by al-mcintyre** [comment]
Hi @xingjianfeng100,

The positions file will depend on your positions/strain/question of interest and is in no way necessary! If you would prefer to detect probability of methylation for every adenine, simply use the flag `--motif A`or `-m A`. If you have a longer motif of interest, say GATC in E. coli, this would become `--motif GATC`/`-m GATC`. 

If you only want to know the methylation status a select location, you can decrease run time using a positions file (say you only care about the first base on the plus strand in an E. coli assembly, your file should then read `ecoli 0 +`). If you already have a bed file of positions including strands, an easy way to convert formats would be to use cut, for example, `cut -f 1,2,6 filename.bed > positions.txt`.

The test files are provided for the toy example only, and any of them will do. You'll note that one is for m6A positions, one for A positions, and one combined, for comparison.  

Good luck and let me know if you have any trouble!

**Comment by xingjianfeng100** [comment]
Hi @al-mcintyre 
thank you for your advice!
I have got the "eventalign.diffs.6", but it always  failed after using "make_bed.py" to make bed file, and it says
 "Finished extracting signals
Merging files...
/public/softwave/mCaller/make_bed.py:55: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  link = linkage(dm,method='complete',metric='correlation')
Caenorhabditis_elegans.sh: line: 24: 20928 have been killed              
$mcaller/make_bed.py -f $filename/eventalign.diffs.6 -d 1 -t 0.5 --plot"
What seems to be the problem?
Thanks
xingjianfeng
