### ISSUE TITLE
Question about trainning custom m6A model

### ISSUE THREAD

**Issue by weir12** [al-mcintyre/mCaller#5]
Hi, @al-mcintyre 
I tried to use your script to trianning my m6A R9.4 model.But I have noticed that I must provide a file which contain m6A pos and A pos in ref.
Unlucky,I can't provide such completely methylated or canonical  sites.
Can I trainning the model by providing a set of methylated reads and non-methylated reads instead of input locations?
Would you give me some tips about rebuilding your script if you like?
thanks:)

**Comment by al-mcintyre** [comment]
Hi @weir12, 
I haven't implemented this feature yet, but it shouldn't be too difficult to do. 
There are a couple bugs but I will try to update soon to allow users to provide their own labelled tsv files for training.
