### ISSUE TITLE
Invalid options for nanopolish index & make_bed.py

### ISSUE THREAD

**Issue by pterzian** [al-mcintyre/mCaller#6]
I been trying to run mCaller on promethION data and I have some questions.

**1. On nanopolish index :** 
When indexing reads with nanopolish index, argument '-q' is called invalid option, yet it manage to find almost all path to fast5. I don't see any '-q' option in the nanopolish index help.
Would it be recommanded/possible to provide sequencing summary files to make the indexing faster ? Then where in the command line should I add the albacore_output.fastq path ?

**2. On make_bed.py :**
'-m' argument is called invaling option. I guessed that this value is a threshold for a minimum fraction of methylated reads at a genomic position. To run this script I have to put out the 'm' option and therefore I have to keep the default value of 0.5.

**3. On <filename>.eventalign.diffs.6 :**
For this file you give the first seven column names, but I can't see anywhere the meaning the 8th column. Would it be the methylation fraction ? Yet it seems to me that it is a per-reads file (I find duplicated genomic positions), so I thought the fraction would be either 0 or 1..

**Comment by al-mcintyre** [comment]
1. Please follow the latest recommendations from nanopolish for indexing (ie. use the option `-s sequencing_summary.txt` for increased speed - see [nanopolish github](https://github.com/jts/nanopolish).) I will update the README soon. 

2. The new flag for the modification threshold is `-t` to avoid confusion with the `-m` flag for motif in the main script (but unfortunately to generate new confusion when I don't update the README - thanks for letting me know). 

3. The last column is the probability of methylation predicted by mCaller for that position and read (read names are in column 2).

**Comment by pterzian** [comment]
Many thanks for your time.

I would need a bit more clarification about the make_bed.py parameters. 

In the description of the **--mod_threshold** parameters you are using the symbol **%%**, does it refer to a minimum **probability** ? Then the default value (0.5) would never include non-methylated bases in make_bed.py's output ?

You are also using this **%%** symbol for the **--positions** parameter. What are you calculating ? Is it a synthesis of all methylation probability at a genomic position ? If indeed **%%** means **probability**, Does it mean mCaller don't calculate the fraction of methylated reads at genomic positions ?

**Comment by al-mcintyre** [comment]
If you run `make_bed.py --help`, the `%%`s in the code should read %, or percent. 

The `--mod_threshold` is the minimum fraction of observations of a position (ie. currents deviations in individual reads) labelled as methylated, based on a >= 50% predicted probability of methylation with the mCaller model. You can change this to 0 if you would like to include bases predicted as unmethylated in the output file. 

The `--positions` parameter indicates the genomic positions for which you would like to calculate the fraction of "methylated" reads (again, predicated probability of methylation >= 50%).
