### ISSUE TITLE
can I replace bwa with minimap2 for ont data?

### ISSUE THREAD

**Issue by forrwill** [al-mcintyre/mCaller#8]
Hi，
when aligning ont data with reference, I use minimap2 in align process, and I found that when using bwa ,the result bam file is 1.5G, but when I use minimap2, the result bam size is only 12M,
the referencce is Pseudomonas, and genome size is 6.1M and ont data size is 2.1G, extracted using "nanopolish extract ", the command line is as below:
minimap:  minimap2 -a -c -x map-ont micro.fastq reference.fasta| samtools view -Sb - | samtools sort -T /tmp/tmp.sorted -o micro.sort.bam
bwa:  bwa mem -x ont2d -t 4 reference.fasta micro.fastq | samtools view -Sb - | samtools sort -T /tmp/tmp.sorted -o micro1.sort.bam

**Comment by al-mcintyre** [comment]
Hi forrwill, 
You should be able to use minimap2, but the reference genome and reads files look like they may be reversed in your command. From the [minimap2 github page](https://github.com/lh3/minimap2): 
`./minimap2 -ax map-ont ref.fa ont.fq.gz > aln.sam`

**Comment by forrwill** [comment]
thaks for you reply,and I will ccorrect it, but I still have some other questions 
one is that what shold I do 
one is that which model should I choose when I call 6mA for plants or animals? I find two models in github, but what is the difference between these models?
another question is that the position or motif file,  what do you get the file like the testdata, which containing the position of 6mA or A?
thank you, and looking forward to your reply

**Comment by al-mcintyre** [comment]
What version of flowcell did you use to generate your data? They are labelled for R9.4 and R9.5 flowcells. 
You don't need a positions file if you want to call every A as methylated/unmethylated. Simply provide the motif using `-m A`. If you are only interested in specific positions then you can generate a positions file with the same columns as in the example.

**Comment by forrwill** [comment]
thank you,
when I use options '-m A', if the reverse strands of the A will be calling as methylated or unmethylated?
and when I set the option  '-b C -m C ', what type of methylated base will be calling?

**Comment by al-mcintyre** [comment]
Yes, the adenines on the reverse strand will also be called. 

If you set the options to C, methylation calls will be made at cytosine bases. However, at the moment we only provide models for m6A vs A and so you would need to train your own model to identify whatever your cytosine modification of interest is.
