### ISSUE TITLE
Question about m6A result compare with tombo

### ISSUE THREAD

**Issue by hygine** [al-mcintyre/mCaller#9]
hi @ralowe @al-mcintyre  Thanks for share the project , nice work.
 I use mCaller detect m6A meth susses, but when I compared the result with tombo, they are so big big big big big difference，the same sample detect result just like this：

- mCaller result：total meth position ：5954091，overlap with tombo 21876 (0.3%)
- tombo: total methy position：10532279，overlap with mCaller 21876 (0.2%)
- overlap methy position relation ：-0.1
- and i found that the mCaller methy lever higher than tombo two or more 

So, my question is why are these two soft's results so differentiations, and could you give me the answer about these results, and which one close to the reality? 
(my opinion : I suppose to tombo, cause that the methy lever most lower, the higher methy lever gets higher false positive rate)

**Comment by hygine** [comment]
![6mA_cor_sample](https://user-images.githubusercontent.com/11896993/59575864-cb114180-90ef-11e9-97ef-d738bbcb8d33.png)
tips：J01 is mCaller result ,J02 is the tombo result.

**Comment by al-mcintyre** [comment]
Hi @hygine, 

Sorry, I'm a bit confused. To summarize, Tombo calls > 10M sites as methylated, mCaller calls ~6M but you are saying the methylation level from Tombo is lower? Based on what we've seen and report in our paper, I would expect most of the calls from both methods to be false positives. Although our accuracy at any given position rose quite high (depending on motif), if you are making predictions at 10M sites, 90% accuracy would still give ~1M false positives. 

Two questions for you: 
1) What species are you studying/how long is the genome? 
2) Is there a known restriction-modification system for your strain of interest?

**Comment by hygine** [comment]
Thank you for your answer . @al-mcintyre 
I mean mCaller methy lever higher than tombo, not the detect modfication number.
And my species is human, 3G genome.
sorry for that my testing sample have not known restriction-modification system .

I was confused that why was overall rate only have 2%~3% with these two methods ?

**Comment by al-mcintyre** [comment]
Ah ok. In that case, I would be particularly cautious in interpreting the output from either tool. I don't know if you saw [this paper](https://doi.org/10.1186/s12864-019-5754-6)? Anyway, 6mA is expected to be extremely rare in metazoan DNA, if present at all, and may be randomly distributed throughout the genome. That said, you could still try to determine if any motifs in particular appear methylated, starting with the sites predicted by both tools, then those predicted as highly methylated by one or the other.
